# Ratings Play that installs the required software 
# tasks names are self explanatory
- hosts: ratings
  gather_facts: True
  remote_user: ubuntu
  become: yes
  become_method: sudo

  environment: 
    SERVICE_VERSION: v1

  tasks:

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install the package "node"
      become: true
      ansible.builtin.apt:
        pkg: nodejs

    - name: Install the package "npm"
      become: true
      ansible.builtin.apt:
        pkg: npm

    - name: run "apt-get install curl --no-install-recommends -y "
      shell: apt-get install curl --no-install-recommends -y 

    - name: run "rm -rf /var/lib/apt/lists/*"
      shell: rm -rf /var/lib/apt/lists/*
    
    - name: Update apt packages
      become: true
      apt:
        update_cache: yes

    - name: Add details.rb file
      copy:
        src: /home/vagrant/project/app/samples/bookinfo/src/ratings/package.json
        dest: /opt/microservices/

    - name: Add details.rb file
      copy:
        src: /home/vagrant/project/app/samples/bookinfo/src/ratings/ratings.js
        dest: /opt/microservices/

    - name: run "npm install"
      shell: npm install
      args:
        chdir: /opt/microservices
 
    - name: run details.rb script
      shell: node /opt/microservices/ratings.js 9080
      async: 1000000
      poll: 0